import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh" className="h-full">
      <body className={inter.className + ' h-full'}>
        <Toaster richColors position="top-center" expand={true} />
        {children}
      </body>
      <Script src="https://unpkg.com/@antv/g2/dist/g2.min.js" />
    </html>
  );
}
