apiVersion: v1
kind: Service
metadata:
  name: mac1
  namespace: namespace-workflow-1744624376021
  labels:
    app.kubernetes.io/name: mac1
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mac1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000