apiVersion: v1
kind: Service
metadata:
  name: mac
  namespace: namespace-workflow-1744623339384
  labels:
    app.kubernetes.io/name: mac
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mac
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000