name: Menu Service CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'menu-service/**'
      - 'audit-sdk/**'
      - '.github/workflows/menu-service.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Tencent Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENTCLOUD_USERNAME }}
          password: ${{ secrets.TENCENTCLOUD_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./menu-service/Dockerfile
          push: true
          tags: ccr.ccs.tencentyun.com/tpctpc/lb:menu-service-${{ github.sha }}
      
      - name: Setup kubectl
        uses: Azure/setup-kubectl@v3
      
      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.K3S_KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      - name: Update deployment
        run: |
          kubectl set image deployment/menu-service menu-service=ccr.ccs.tencentyun.com/tpctpc/lb:menu-service-${{ github.sha }} --record
      
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/menu-service